// <auto-generated />
namespace AdelanteRedo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Programs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Programs));
        
        string IMigrationMetadata.Id
        {
            get { return "201611011825327_Programs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
