//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdelanteRedo.Models
{
    using System;
    using System.Collections.Generic;
    
    public class Donor
    {
        public int DonorID { get; set; }
        public string Donor_FirstName { get; set; }
        public string Donor_LastName { get; set; }
        public string Donor_Address { get; set; }
        public string Donor_City { get; set; }
        public string Donor_State { get; set; }
        public string Donor_Zip { get; set; }
        public string Donor_HomeTele { get; set; }
        public string Donor_CellPhone { get; set; }
        public string Donor_Email { get; set; }
    }
}
