//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AdelanteRedo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingStaffAttendance
    {
        public int MeetingStaffAttendanceID { get; set; }
        public int StaffID { get; set; }
        public int MeetingID { get; set; }
        public Nullable<bool> Attendance { get; set; }
    
        public virtual Meeting Meeting { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
