//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdelanteRedo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meeting()
        {
            this.MeetingStudentAttendance = new HashSet<MeetingStudentAttendance>();
            this.MeetingStaffAttendance = new HashSet<MeetingStaffAttendance>();
            this.MeetingVolunteerAttendance = new HashSet<MeetingVolunteerAttendance>();
        }
    
        public int MeetingID { get; set; }

        public System.DateTime Meeting_Start { get; set; }
        public System.DateTime Meeting_End { get; set; }
        public string Meeting_Type { get; set; }
        public string Location_Name { get; set; }
    
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingStudentAttendance> MeetingStudentAttendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingStaffAttendance> MeetingStaffAttendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingVolunteerAttendance> MeetingVolunteerAttendance { get; set; }
    }
}
