//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdelanteRedo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volunteer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    
        public  Guid VolunteerID { get; set; }
        public string Volunteer_FirstName { get; set; }
        public string Volunteer_LastName { get; set; }
        public string Volunteer_Address { get; set; }
        public string Volunteer_City { get; set; }
        public string Volunteer_State { get; set; }
        public string Volunteer_Zip { get; set; }
        public string Volunteer_HomeTele { get; set; }
        public string Volunteer_CellPhone { get; set; }
        public string Volunteer_Email { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
    }
}
