//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingStaffAttendance
    {
        public string Staff_NUM { get; set; }
        public decimal Meeting_NUM { get; set; }
        public Nullable<bool> Attendance { get; set; }
    
        public virtual Meeting Meeting { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
