//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public string Staff_NUM { get; set; }
        public string Staff_FirstName { get; set; }
        public string Staff_LastName { get; set; }
        public string Staff_Address { get; set; }
        public string Staff_City { get; set; }
        public string Staff_State { get; set; }
        public string Staff_Zip { get; set; }
        public string Staff_HomeTele { get; set; }
        public string Staff_CellPhone { get; set; }
        public string Staff_Email { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
    }
}
